cd /home/zemar/Repositories/42-common-core/projects/01_libft/src

./myprogram ft_isalpha
./myprogram ft_isdigit
./myprogram ft_isalnum
./myprogram ft_isascii
./myprogram ft_isprint
./myprogram ft_strlen
./myprogram ft_memset
./myprogram ft_bzero
./myprogram ft_memcpy
./myprogram ft_memmove
./myprogram ft_strlcpy
./myprogram ft_strlcat
./myprogram ft_toupper
./myprogram ft_tolower
./myprogram ft_strchr
./myprogram ft_strrchr
./myprogram ft_strncmp
./myprogram ft_memchr
./myprogram ft_memcmp
./myprogram ft_strnstr
./myprogram ft_atoi
./myprogram ft_calloc
./myprogram ft_strdup
./myprogram ft_substr
./myprogram ft_strjoin
./myprogram ft_strtrim
./myprogram ft_split
./myprogram ft_itoa
./myprogram ft_strmapi
./myprogram ft_striteri
./myprogram ft_putchar_fd
./myprogram ft_putstr_fd
./myprogram ft_putendl_fd
./myprogram ft_putnbr_fd
./myprogram ft_lstnew
./myprogram ft_lstadd_front
./myprogram ft_lstsize
./myprogram ft_lstlast
./myprogram ft_lstadd_back
./myprogram ft_lstdelone
./myprogram ft_lstclear
./myprogram ft_lstmap

cd -